//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryFaculty.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilitaryFaculty.Domain.Resources.EnumStrings", typeof(EnumStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доцент.
        /// </summary>
        internal static string AcademicDegree_Docent {
            get {
                return ResourceManager.GetString("AcademicDegree_Docent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string AcademicDegree_None {
            get {
                return ResourceManager.GetString("AcademicDegree_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессор.
        /// </summary>
        internal static string AcademicDegree_Professor {
            get {
                return ResourceManager.GetString("AcademicDegree_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидат наук.
        /// </summary>
        internal static string AcademicRank_CandidateOfScience {
            get {
                return ResourceManager.GetString("AcademicRank_CandidateOfScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктор наук.
        /// </summary>
        internal static string AcademicRank_DoctorOfScience {
            get {
                return ResourceManager.GetString("AcademicRank_DoctorOfScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        internal static string AcademicRank_None {
            get {
                return ResourceManager.GetString("AcademicRank_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебник.
        /// </summary>
        internal static string BookType_Schoolbook {
            get {
                return ResourceManager.GetString("BookType_Schoolbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебное пособие.
        /// </summary>
        internal static string BookType_Tutorial {
            get {
                return ResourceManager.GetString("BookType_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полностью соответствует.
        /// </summary>
        internal static string ConferenceAccordance_Fully {
            get {
                return ResourceManager.GetString("ConferenceAccordance_Fully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не соответствует.
        /// </summary>
        internal static string ConferenceAccordance_None {
            get {
                return ResourceManager.GetString("ConferenceAccordance_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частично соответствует.
        /// </summary>
        internal static string ConferenceAccordance_Partly {
            get {
                return ResourceManager.GetString("ConferenceAccordance_Partly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международная.
        /// </summary>
        internal static string EventLevel_International {
            get {
                return ResourceManager.GetString("EventLevel_International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Республиканская.
        /// </summary>
        internal static string EventLevel_Republican {
            get {
                return ResourceManager.GetString("EventLevel_Republican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вузовская.
        /// </summary>
        internal static string EventLevel_University {
            get {
                return ResourceManager.GetString("EventLevel_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом (грамота).
        /// </summary>
        internal static string ExhibitionAward_Certificate {
            get {
                return ResourceManager.GetString("ExhibitionAward_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом первой степени.
        /// </summary>
        internal static string ExhibitionAward_FirstDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_FirstDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом второй степени.
        /// </summary>
        internal static string ExhibitionAward_SecondDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_SecondDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом третьей степени.
        /// </summary>
        internal static string ExhibitionAward_ThirdDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_ThirdDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-историческая работа организована, но ведется с отдельными недостатками.
        /// </summary>
        internal static string HistoricalWorkOrganization_Custom {
            get {
                return ResourceManager.GetString("HistoricalWorkOrganization_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-историческая работа организована и ведется в соответствии с требованиями нормативных правовых актов.
        /// </summary>
        internal static string HistoricalWorkOrganization_Full {
            get {
                return ResourceManager.GetString("HistoricalWorkOrganization_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-историческая работа не организована.
        /// </summary>
        internal static string HistoricalWorkOrganization_None {
            get {
                return ResourceManager.GetString("HistoricalWorkOrganization_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аспирант.
        /// </summary>
        internal static string JobPosition_Aspirant {
            get {
                return ResourceManager.GetString("JobPosition_Aspirant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доцент.
        /// </summary>
        internal static string JobPosition_Docent {
            get {
                return ResourceManager.GetString("JobPosition_Docent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Докторант.
        /// </summary>
        internal static string JobPosition_Doctorant {
            get {
                return ResourceManager.GetString("JobPosition_Doctorant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник кафедры.
        /// </summary>
        internal static string JobPosition_HeadOfCathedra {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfCathedra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник цикла.
        /// </summary>
        internal static string JobPosition_HeadOfCycle {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник факультета.
        /// </summary>
        internal static string JobPosition_HeadOfFaculty {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессор.
        /// </summary>
        internal static string JobPosition_Professor {
            get {
                return ResourceManager.GetString("JobPosition_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старший преподаватель.
        /// </summary>
        internal static string JobPosition_SeniorProfessor {
            get {
                return ResourceManager.GetString("JobPosition_SeniorProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсант/Студент.
        /// </summary>
        internal static string JobPosition_Student {
            get {
                return ResourceManager.GetString("JobPosition_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель.
        /// </summary>
        internal static string JobPosition_Teacher {
            get {
                return ResourceManager.GetString("JobPosition_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капитан.
        /// </summary>
        internal static string MilitaryRank_Captain {
            get {
                return ResourceManager.GetString("MilitaryRank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полковник.
        /// </summary>
        internal static string MilitaryRank_Colonel {
            get {
                return ResourceManager.GetString("MilitaryRank_Colonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Младший лейтенант.
        /// </summary>
        internal static string MilitaryRank_JuniorLieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_JuniorLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лейтенант.
        /// </summary>
        internal static string MilitaryRank_Lieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подполковник.
        /// </summary>
        internal static string MilitaryRank_LieutenantColonel {
            get {
                return ResourceManager.GetString("MilitaryRank_LieutenantColonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майор.
        /// </summary>
        internal static string MilitaryRank_Major {
            get {
                return ResourceManager.GetString("MilitaryRank_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старший лейтенант.
        /// </summary>
        internal static string MilitaryRank_SeniorLieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_SeniorLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа научного кружка курсантов (студентов) организована, но ведется с отдельными недостатками.
        /// </summary>
        internal static string MilitaryScientificSocietyOrganization_Custom {
            get {
                return ResourceManager.GetString("MilitaryScientificSocietyOrganization_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа научного кружка курсантов (студентов) организована и ведется в соответствии с требованиями нормативных правовых актов.
        /// </summary>
        internal static string MilitaryScientificSocietyOrganization_Full {
            get {
                return ResourceManager.GetString("MilitaryScientificSocietyOrganization_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Работа научного кружка курсантов (студентов) не организована.
        /// </summary>
        internal static string MilitaryScientificSocietyOrganization_None {
            get {
                return ResourceManager.GetString("MilitaryScientificSocietyOrganization_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-научное сопровождение проведено.
        /// </summary>
        internal static string MilitaryScientificSupportState_Completed {
            get {
                return ResourceManager.GetString("MilitaryScientificSupportState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-научное сопровождение не проведено.
        /// </summary>
        internal static string MilitaryScientificSupportState_NotCompleted {
            get {
                return ResourceManager.GetString("MilitaryScientificSupportState_NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализированный совет по защите диссертаций.
        /// </summary>
        internal static string ParticipationPlace_DefenceOfDissertationCounsil {
            get {
                return ResourceManager.GetString("ParticipationPlace_DefenceOfDissertationCounsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакционная коллегия научных изданий.
        /// </summary>
        internal static string ParticipationPlace_EditorialBoardsOfScientificPublications {
            get {
                return ResourceManager.GetString("ParticipationPlace_EditorialBoardsOfScientificPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспертный совет ВАК Беларуси.
        /// </summary>
        internal static string ParticipationPlace_HigherAttestationCommission {
            get {
                return ResourceManager.GetString("ParticipationPlace_HigherAttestationCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-научный или научно-технический совет вуза.
        /// </summary>
        internal static string ParticipationPlace_ResearchCounsil {
            get {
                return ResourceManager.GetString("ParticipationPlace_ResearchCounsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка научно-педагогических работников высшей квалификации организована, но ведется с отдельными недостатками.
        /// </summary>
        internal static string ProfsOrganization_Custom {
            get {
                return ResourceManager.GetString("ProfsOrganization_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка научно-педагогических работников высшей квалификации организована и ведется в соответствии с требованиями нормативных правовых актов.
        /// </summary>
        internal static string ProfsOrganization_Full {
            get {
                return ResourceManager.GetString("ProfsOrganization_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подготовка научно-педагогических работников высшей квалификации не организована.
        /// </summary>
        internal static string ProfsOrganization_None {
            get {
                return ResourceManager.GetString("ProfsOrganization_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нерецензируемая научная статья.
        /// </summary>
        internal static string PublicationType_Article {
            get {
                return ResourceManager.GetString("PublicationType_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монография.
        /// </summary>
        internal static string PublicationType_Monograph {
            get {
                return ResourceManager.GetString("PublicationType_Monograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензируемая научная статья.
        /// </summary>
        internal static string PublicationType_ReviewedArticle {
            get {
                return ResourceManager.GetString("PublicationType_ReviewedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тезис докладов.
        /// </summary>
        internal static string PublicationType_Thesis {
            get {
                return ResourceManager.GetString("PublicationType_Thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С отрицательным ответом.
        /// </summary>
        internal static string ScientificRequestResponce_Negative {
            get {
                return ResourceManager.GetString("ScientificRequestResponce_Negative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С положительным ответом.
        /// </summary>
        internal static string ScientificRequestResponce_Positive {
            get {
                return ResourceManager.GetString("ScientificRequestResponce_Positive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на изобретение.
        /// </summary>
        internal static string ScientificRequestType_Invention {
            get {
                return ResourceManager.GetString("ScientificRequestType_Invention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на полезную модель.
        /// </summary>
        internal static string ScientificRequestType_UtilityModel {
            get {
                return ResourceManager.GetString("ScientificRequestType_UtilityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принята.
        /// </summary>
        internal static string SuggestionState_Accepted {
            get {
                return ResourceManager.GetString("SuggestionState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не принята.
        /// </summary>
        internal static string SuggestionState_Denied {
            get {
                return ResourceManager.GetString("SuggestionState_Denied", resourceCulture);
            }
        }
    }
}
