//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilitaryFaculty.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilitaryFaculty.Resources.EnumStrings", typeof(EnumStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доцент.
        /// </summary>
        public static string AcademicDegree_Docent {
            get {
                return ResourceManager.GetString("AcademicDegree_Docent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        public static string AcademicDegree_None {
            get {
                return ResourceManager.GetString("AcademicDegree_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессор.
        /// </summary>
        public static string AcademicDegree_Professor {
            get {
                return ResourceManager.GetString("AcademicDegree_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кандидат наук.
        /// </summary>
        public static string AcademicRank_CandidateOfScience {
            get {
                return ResourceManager.GetString("AcademicRank_CandidateOfScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доктор наук.
        /// </summary>
        public static string AcademicRank_DoctorOfScience {
            get {
                return ResourceManager.GetString("AcademicRank_DoctorOfScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствует.
        /// </summary>
        public static string AcademicRank_None {
            get {
                return ResourceManager.GetString("AcademicRank_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Одобрено.
        /// </summary>
        public static string ApplicationStatus_Accepted {
            get {
                return ResourceManager.GetString("ApplicationStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рассматривается.
        /// </summary>
        public static string ApplicationStatus_Applied {
            get {
                return ResourceManager.GetString("ApplicationStatus_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебник.
        /// </summary>
        public static string BookType_Schoolbook {
            get {
                return ResourceManager.GetString("BookType_Schoolbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учебное пособие.
        /// </summary>
        public static string BookType_Tutorial {
            get {
                return ResourceManager.GetString("BookType_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полностью соответствует.
        /// </summary>
        public static string ConferenceAccordance_Fully {
            get {
                return ResourceManager.GetString("ConferenceAccordance_Fully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не соответствует.
        /// </summary>
        public static string ConferenceAccordance_None {
            get {
                return ResourceManager.GetString("ConferenceAccordance_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Частично соответствует.
        /// </summary>
        public static string ConferenceAccordance_Partly {
            get {
                return ResourceManager.GetString("ConferenceAccordance_Partly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализированный совет по защите диссертаций.
        /// </summary>
        public static string CouncilType_DefenceOfDissertationsCouncil {
            get {
                return ResourceManager.GetString("CouncilType_DefenceOfDissertationsCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редакционная коллегия научных изданий.
        /// </summary>
        public static string CouncilType_EditorialBoardCouncil {
            get {
                return ResourceManager.GetString("CouncilType_EditorialBoardCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Военно-научный или научно-технический совет вуза.
        /// </summary>
        public static string CouncilType_ResearchCounsil {
            get {
                return ResourceManager.GetString("CouncilType_ResearchCounsil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспертный совет ВАК Беларуси.
        /// </summary>
        public static string CouncilType_SupremeCertificationCommissionCouncil {
            get {
                return ResourceManager.GetString("CouncilType_SupremeCertificationCommissionCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Защищена.
        /// </summary>
        public static string DissertationState_Defenced {
            get {
                return ResourceManager.GetString("DissertationState_Defenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрабатывается.
        /// </summary>
        public static string DissertationState_Development {
            get {
                return ResourceManager.GetString("DissertationState_Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Международная.
        /// </summary>
        public static string EventLevel_International {
            get {
                return ResourceManager.GetString("EventLevel_International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Республиканская.
        /// </summary>
        public static string EventLevel_Republican {
            get {
                return ResourceManager.GetString("EventLevel_Republican", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вузовская.
        /// </summary>
        public static string EventLevel_University {
            get {
                return ResourceManager.GetString("EventLevel_University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом (грамота).
        /// </summary>
        public static string ExhibitionAward_Certificate {
            get {
                return ResourceManager.GetString("ExhibitionAward_Certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом первой степени.
        /// </summary>
        public static string ExhibitionAward_FirstDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_FirstDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом второй степени.
        /// </summary>
        public static string ExhibitionAward_SecondDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_SecondDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диплом третьей степени.
        /// </summary>
        public static string ExhibitionAward_ThirdDegree {
            get {
                return ResourceManager.GetString("ExhibitionAward_ThirdDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на изобретение.
        /// </summary>
        public static string InventiveApplicationType_Invention {
            get {
                return ResourceManager.GetString("InventiveApplicationType_Invention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на полезную модель.
        /// </summary>
        public static string InventiveApplicationType_UtilityModel {
            get {
                return ResourceManager.GetString("InventiveApplicationType_UtilityModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адъюнкт очной формы обучения.
        /// </summary>
        public static string JobPosition_AdjunctFullTime {
            get {
                return ResourceManager.GetString("JobPosition_AdjunctFullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адъюнкт заочной формы обучения.
        /// </summary>
        public static string JobPosition_AdjunctPartTime {
            get {
                return ResourceManager.GetString("JobPosition_AdjunctPartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доцент.
        /// </summary>
        public static string JobPosition_Docent {
            get {
                return ResourceManager.GetString("JobPosition_Docent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Докторант.
        /// </summary>
        public static string JobPosition_Doctoral {
            get {
                return ResourceManager.GetString("JobPosition_Doctoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник кафедры.
        /// </summary>
        public static string JobPosition_HeadOfCathedra {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfCathedra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник цикла.
        /// </summary>
        public static string JobPosition_HeadOfCycle {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начальник факультета.
        /// </summary>
        public static string JobPosition_HeadOfFaculty {
            get {
                return ResourceManager.GetString("JobPosition_HeadOfFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессор.
        /// </summary>
        public static string JobPosition_Professor {
            get {
                return ResourceManager.GetString("JobPosition_Professor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старший преподаватель.
        /// </summary>
        public static string JobPosition_SeniorProfessor {
            get {
                return ResourceManager.GetString("JobPosition_SeniorProfessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель.
        /// </summary>
        public static string JobPosition_Teacher {
            get {
                return ResourceManager.GetString("JobPosition_Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсант/Студент.
        /// </summary>
        public static string JobPosition_Сadet {
            get {
                return ResourceManager.GetString("JobPosition_Сadet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Капитан.
        /// </summary>
        public static string MilitaryRank_Captain {
            get {
                return ResourceManager.GetString("MilitaryRank_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полковник.
        /// </summary>
        public static string MilitaryRank_Colonel {
            get {
                return ResourceManager.GetString("MilitaryRank_Colonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Младший лейтенант.
        /// </summary>
        public static string MilitaryRank_JuniorLieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_JuniorLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лейтенант.
        /// </summary>
        public static string MilitaryRank_Lieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_Lieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подполковник.
        /// </summary>
        public static string MilitaryRank_LieutenantColonel {
            get {
                return ResourceManager.GetString("MilitaryRank_LieutenantColonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Майор.
        /// </summary>
        public static string MilitaryRank_Major {
            get {
                return ResourceManager.GetString("MilitaryRank_Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Личный состав.
        /// </summary>
        public static string MilitaryRank_None {
            get {
                return ResourceManager.GetString("MilitaryRank_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старший лейтенант.
        /// </summary>
        public static string MilitaryRank_SeniorLieutenant {
            get {
                return ResourceManager.GetString("MilitaryRank_SeniorLieutenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нерецензируемая научная статья.
        /// </summary>
        public static string PublicationType_Article {
            get {
                return ResourceManager.GetString("PublicationType_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Монография.
        /// </summary>
        public static string PublicationType_Monograph {
            get {
                return ResourceManager.GetString("PublicationType_Monograph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рецензируемая научная статья.
        /// </summary>
        public static string PublicationType_ReviewedArticle {
            get {
                return ResourceManager.GetString("PublicationType_ReviewedArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тезис докладов.
        /// </summary>
        public static string PublicationType_Thesis {
            get {
                return ResourceManager.GetString("PublicationType_Thesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не проведено.
        /// </summary>
        public static string ResearchMaintainState_NotPerformed {
            get {
                return ResourceManager.GetString("ResearchMaintainState_NotPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проведено.
        /// </summary>
        public static string ResearchMaintainState_Performed {
            get {
                return ResourceManager.GetString("ResearchMaintainState_Performed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принята.
        /// </summary>
        public static string SuggestionState_Accepted {
            get {
                return ResourceManager.GetString("SuggestionState_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не принята.
        /// </summary>
        public static string SuggestionState_Denied {
            get {
                return ResourceManager.GetString("SuggestionState_Denied", resourceCulture);
            }
        }
    }
}
